-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT '2a55d4f486701b8e' HASH '9b821527cab46300549e9d5430f3faa1d794df88ad9ea410ab0c072e837569e6' ADMIN;         
CREATE SEQUENCE "PUBLIC"."PRODUCT_QUANTITY_SEQ" START WITH 1 INCREMENT BY 50; 
CREATE SEQUENCE "PUBLIC"."PRODUCT_SEQ" START WITH 1 INCREMENT BY 50;          
CREATE MEMORY TABLE "PUBLIC"."PRODUCT"(
    "PRICE" INTEGER NOT NULL,
    "STOCK" INTEGER NOT NULL,
    "ID" BIGINT NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PICTURE" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT; 
CREATE MEMORY TABLE "PUBLIC"."PRODUCT_QUANTITY"(
    "SUM" INTEGER NOT NULL,
    "ID" BIGINT NOT NULL,
    "PRODUCT_ID" BIGINT
);         
ALTER TABLE "PUBLIC"."PRODUCT_QUANTITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT_QUANTITY;        
ALTER TABLE "PUBLIC"."PRODUCT_QUANTITY" ADD CONSTRAINT "PUBLIC"."FKI5BXAXET5YF16AJ98DT7S064P" FOREIGN KEY("PRODUCT_ID") REFERENCES "PUBLIC"."PRODUCT"("ID") NOCHECK;          
